### ISSUE TITLE
quick start guide suggestions

### ISSUE THREAD

**Issue by duncancallaway** [NREL-Sienna/PowerSimulationsDynamics.jl#341]
1. at the line 

"julia> sim = Simulation!(ResidualModel, omib_sys, pwd(), time_span, perturbation_trip)"
--> suggest you explain briefly what the residual model is, contrast it to massmatrixmodel and say where to learn more.  

2. Consider giving a little guidance to people that are new to Julia on learning more about functions.  For example in the REPL type "? Simulation" to learn more about the function.

3. At the line "julia> x0_init = read_initial_conditions(sim)" explain how these initial conditions are generated.  E.g.: do they come from the raw file, from PowerSimulations, or from PSID?

4. function "small_signal_analysis" does not have any help docs. 

5. After text "Explore participation factors. In this case for state ω" the cell block shows pf for both \omega and \delta.

6.  need "using Plots" before calling plots.  

7.  When I run the line "plot(angle, xlabel = "time", ylabel = "rotor angle [rad]", label = "gen-102-1")" the plot looks like this: 
<img width="601" alt="image" src="https://github.com/NREL-Sienna/PowerSimulationsDynamics.jl/assets/11277405/eb8a9f0b-768d-4dc6-929e-74e0bee37c43">

**Comment by jd-lara** [comment]
@duncancallaway the quick start guide is now fixed. We added a reference to the tutorial for more in depth details since the case is the same and we wanted to keep the getting started more light weight. Thanks for the comments.
