### ISSUE TITLE
Typos in documents: LCL Filter state-space model reference frame should be on the dq0 axis.

### ISSUE THREAD

**Issue by XingyuCiao** [NREL-Sienna/PowerSimulationsDynamics.jl#356]
Hi! The correct model should be:
![LCL-ss](https://github.com/NREL-Sienna/PowerSimulationsDynamics.jl/assets/149185686/377f4cf5-0e89-441d-af6f-0985308f349f)

**Comment by rodrigomha** [comment]
Hi, is the only difference that we use R and I instead of DQ? This is just a convention that we use to refer to the reference frame of the network as RI instead of the internal reference frames of dq used for devices.

**Comment by XingyuCiao** [comment]
> Hi, is the only difference that we use R and I instead of DQ? This is just a convention that we use to refer to the reference frame of the network as RI instead of the internal reference frames of dq used for devices.
Hi, that makes sense to me. 
Just one more small typo, for eq(1e) and (1f), the filter current i_r and i_i should be used instead of converter current i_r,cv and i_i,cv.

**Comment by rodrigomha** [comment]
> > Hi, is the only difference that we use R and I instead of DQ? This is just a convention that we use to refer to the reference frame of the network as RI instead of the internal reference frames of dq used for devices.
> 
> Hi, that makes sense to me. Just one more small typo, for eq(1e) and (1f), the filter current i_r and i_i should be used instead of converter current i_r,cv and i_i,cv.

Thanks for this. I'll fix this typo in the next release!

**Comment by jd-lara** [comment]
@rodrigomha can we fix this for the 0.13 release?
